Repository GTNewHorizons/Hodgepodge, pull requests merged in 2025-05, with the labels that each got.

#521 Remove recursive slotClick calls when shift clicking a slot
  src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
  src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
  src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinContainer_FixShiftRecursion.java
Labels: bug, enhancement

#512 Enderman Griefing Configs
  README.md
  src/main/java/com/mitchej123/hodgepodge/config/TweaksConfig.java
  src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
  src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinEntityEndermanGrab.java
  src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinEntityEndermanPlace.java
  src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinEntityEndermanPlaceBlacklist.java
Labels: enhancement

#544 Add Mixins to fix Redstone output for Extra Utilities Chests not updating on Inventory Change
  src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
  src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
  src/main/java/com/mitchej123/hodgepodge/mixins/late/extrautilities/MixinExtraUtilsChest.java
Labels: :construction: Testing on Zeta
